# Generated by Django 3.1.3 on 2020-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('edu', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=30)),
                ('state', models.CharField(default='', max_length=1000)),
                ('benefits', models.CharField(max_length=3000)),
                ('desc', models.CharField(max_length=3000)),
                ('url', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
